#!/bin/bash

# adapted from scandocs(https://stackoverflow.com/a/14537727)

if [[ "$OSTYPE" == "linux-gnu"* ]]; then
    doc_to_text='catdoc'
    docx_to_text='docx2txt <'

elif [[ "$OSTYPE" == "darwin"* ]]; then
    doc_to_text='textutil -stdout -cat txt'
    docx_to_text='textutil -stdout -cat txt'

else
    echo Un-supported OS: $OSTYPE
fi

find . -name "*.doc" -maxdepth 1 | 
    while read i; do $doc_to_text "$i" | 
        grep --color=auto -iH --label="$i" "$1"; done
find . -name "*.docx" -maxdepth 1 | 
    while read i; do $docx_to_text "$i" | 
        grep --color=auto -iH --label="$i" "$1"; done
